app = 'trmnl-apple-photos'
primary_region = 'arn'

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"
  max_unavailable = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
